### ISSUE TITLE
upgrade to go 1.22 ?

### ISSUE THREAD

**Issue by gedw99** [nevkontakte/go-app-on-gopherjs#1]
Hey @nevkontakte 

I am looking into using gophers for projects and this repo is quite a good example of the practical aspects of using and evaluating gophers ? 

Was wondering how hard it would be to upgrade it to latest golang ?

BTW I use gobrew to easily run many golang versions. it can detect the go version inside each golang module and install it on the fly.  Might be useful for this ... 
It is itself written in golang. 
The big advantage is that it leaves your normal golang completely alone and does not mess with it. I make a make include that does exactly this so I can reuse it on all projects.

**Comment by nevkontakte** [comment]
There is currently active work to add [generics](https://github.com/gopherjs/gopherjs/issues/1013) and [Go 1.20](https://github.com/gopherjs/gopherjs/issues/1270) support. Once that work is complete, support for newer versions of Go will follow.

As to this repository - it's an okay demo, although it served more of a proof-of-concept purpose for the [go-app framework](https://github.com/maxence-charriere/go-app) running under GopherJS instead of WebAssembly.

**Comment by nevkontakte** [comment]
> Are you "supported" by google like the tinygo team is or this is a labour of love as they say ?

Nope, GopherJS is not affiliated with Google in any way. I work on it mostly because it's an interesting problem to play with :) I know some of the people who contribute to the project do use it in the professional context.
